### ISSUE TITLE
No button to close image view

### ISSUE THREAD

**Issue by hermann-san** [kartaview/openstreetcam.org#334]
when I'm viewing a photo / image I would like to return directly back to the map and it seem logical to me to click the X button to get there, but instead it takes me to my profile. I assume it was not meant to be that way, right?  There seems to be no other way to get directly  back to the map other than clicking the browser back button.

The X button I mean is in the left upper corner (where the red arrow is )
![Auswahl_003](https://user-images.githubusercontent.com/7679654/123454361-c0dc8480-d5e0-11eb-868b-8736b4acd7b8.png)

**Comment by zhaitianduo** [comment]
Hey, thanks for the valuable feedback! Will take a look with the team and fix this.

**Comment by brmonaghan** [comment]
Thanks. I wanted it to go back to map, NOT on profile

**Comment by zhaitianduo** [comment]
Hey this issue is fixed, please give it a try.

Thanks for your valuable feedback again!

**Comment by brmonaghan** [comment]
@zhaitianduo its still not working on my snowcool776 account but it works on my computer geek account
![still not working](https://user-images.githubusercontent.com/71337477/125780628-b7c4870d-3447-4d96-903a-a1cd5de303db.png)
https://kartaview.org/details/1566873
https://kartaview.org/details/1566193
https://kartaview.org/details/1456702
https://kartaview.org/details/1455626
